pool: Default
trigger: 
  - master
steps:
  - task: Docker@2
    inputs:  
      containerRegistry: Docker Registry
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: '5.0-$(Build.BuildId)'
  - script: echo $(Build.BuildId)
